dist: trusty   # Use Ubuntu 14.04 image (instead of 12.04)
language: r
sudo: false
r: 3.4.1

branches:
  only:
    - master
    - develop

install:
  - R -e 'if (system.file(package="packrat") == "") install.packages("packrat")'
  - R -e "packrat::packify(); packrat::restore()"


script:
  - R -f tests/test-all.R

#TODO: coverage and check this actually works
