dist: trusty   # Use Ubuntu 14.04 image (instead of 12.04)
language: r
sudo: false
r: 3.4.1

# getting travis error when installing Installing units (0.6-4) ...
addons:
  apt:
    packages:
      - libudunits2-dev

branches:
  only:
    - master
    - develop

install:
  # to solve travis ci error when installing V8
<<<<<<< HEAD
  - R -e 'source("https://install-github.me/r-lib/remotes")'
=======
  R -e 'source("https://install-github.me/r-lib/remotes")'
>>>>>>> 1614aaf34d9f0a0a92b50a162773c86b710726b9
  - R -e 'if (system.file(package="packrat") == "") install.packages("packrat")'
  - R -e "packrat::packify(); packrat::restore()"


script:
  - R -f tests/test-all.R

#TODO: coverage and check this actually works
