language: r
sudo: false
r: 3.4.1

# getting travis error when installing Installing units (0.6-4) ...
addons:
  apt:
    packages:
      - libudunits2-dev
      - libv8-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libjq-dev
      - libgeos-dev
      - libgdal-dev
      - libnetcdf-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); covr::codecov(coverage = covr::file_coverage('R/police-selectize-functions.R', 'tests/test-all.R'))'


branches:
  only:
    - master
    - develop

install:
  - R -e 'if (system.file(package="packrat") == "") install.packages("packrat")'
  - R -e "packrat::packify(); packrat::restore()"


script:
  - R -f tests/test-all.R

#TODO: coverage and check this actually works
